config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  concern :voteable do
    member do
      patch :upvote
      patch :downvote
    end
  end

  root 'questions#index'

  resources :questions, only: [:index, :show, :new, :create, :update, :destroy], concerns: [:voteable] do
    resources :answers, only: [:create, :update, :destroy], concerns: [:voteable], shallow: true do
      member { patch :mark_as_best }
    end
  end

  resources :attachments, only: :destroy
  resources :links, only: :destroy
  resources :trophies, only: :index
end

app/models/question.rb
class Question < ApplicationRecord
  include Voteable

  belongs_to :user
  belongs_to :best_answer, class_name: 'Answer', optional: true
  has_one :trophy, dependent: :destroy
  has_many :answers, dependent: :destroy
  has_many :links, dependent: :destroy, as: :linkable

  has_many_attached :files

  accepts_nested_attributes_for :links, reject_if: :all_blank
  accepts_nested_attributes_for :trophy, reject_if: :all_blank

  validates :title, :body, presence: true

  def append_files=(attachables)
    files.attach(attachables)
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  include Voted

  before_action :authenticate_user!, except: %i[index show]
  before_action :find_question, only: %i[show update destroy]

  def index
    @questions = Question.all
  end

  def show
    @best_answer = @question.best_answer
    @other_answers = @question.answers.where.not(id: @question.best_answer_id)
    @answer = @question.answers.new
    @answer.links.new
  end

  def new
    @question = current_user.questions.new
    @question.links.new
    @question.build_trophy
  end

  def create
    @question = current_user.questions.new(question_params)

    if @question.save
      redirect_to @question, notice: t('.success')
    else
      render :new
    end
  end

  def update
    if @question.user == current_user
      flash.now[:notice] = t('.success') if @question.update(question_params)
    end
  end

  def destroy
    if @question.user == current_user
      @question.destroy
      redirect_to @question, notice: t('.success')
    else
      flash.now[:notice] = t('.failure')
      render :show
    end
  end

  private

  def find_question
    @question = Question.with_attached_files.find(params[:id])
  end

  def question_params
    params.require(:question).permit(:title, :body, files: [], append_files: [],
      links_attributes: [:name, :url], trophy_attributes: [:title, :image])
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
  def delete_question(question)
    link_to t('.delete'),
            question_path(question),
            method: :delete,
            data: { confirm: t('.delete_confirmation') }
  end

  def edit_question(question)
    link_to t('.edit'),
            '#',
            class: 'edit-question-link'
  end
end

app/views/questions/_question.html.slim
tr
  td = link_to question.title, question_path(question)
  td = question.body[0, 30]

app/views/questions/index.html.slim
h1 question list
p = link_to 'Ask question', new_question_path

table
  = render @questions

app/views/questions/new.html.slim
= form_with model: @question do |f|
  = render 'shared/errors', resource: @question
  p
    = f.label :title
    = f.text_field :title
  p
    = f.label :body
    = f.text_area :body

  .trophy
    = render 'trophies/trophy_form', f: f

  .links
    = render 'links/link_form_for_creating', f: f

  p
    = f.label :files
    = f.file_field :files, multiple: true, direct_upload: true

  p = f.submit

app/views/questions/show.html.slim
.question
  h1 class='question-title' = @question.title
  p class='question-body' = @question.body

  - if @question.user == current_user
    = form_with model: @question, html: { style: "display: none;" }, local: false do |f|
      .question-errors
      p = f.text_area :title
      p = f.text_area :body
      .links
        = render 'links/link_form_for_editing', f: f
      p = f.file_field :append_files, multiple: true, direct_upload: true
      p = f.submit t('save')

  .question-links
    - if @question.links.present?
      = render @question.links

  .question-files
    - if @question.files.attached?
      = render @question.files

  - if @question.user == current_user
    p = edit_question(@question)
    p = delete_question(@question)

  div style="display: flex;"
    div
      span Rating: 
      span class='rating' = @question.rating
    - unless current_user.blank? || @question.user == current_user
      div style="display: flex; margin-inline-start: 2px;"
        = upvote_button(@question)
        = downvote_button(@question)

- if @question.user == current_user && @question.trophy
  .trophy
    = t('.best_answer_trophy')
    = render @question.trophy

.answers
  table
    = render 'answers/answer', answer: @best_answer, best_answer: true
    = render @other_answers

= render 'answers/new'

p = link_to t('back'), questions_path

app/views/questions/update.js.erb
$('.notice').html('')

<% if @question.errors.present? %>
	$('.question .question-errors').html('<%= render 'shared/errors', resource: @question %>')
<% else %>
	$('.question question-errors').html('')
	$('.question .question-title').show()
	$('.question .question-title').html('<%= j @question.title %>')
	$('.question .question-body').show()
	$('.question .question-body').html('<%= j @question.body %>')
	$('.question .question-files').html('<%= j render @question.files if @question.files.attached? %>')
	$('.question .question-links').html('<%= j render @question.links if @question.links.present? %>')
	$('.question form').hide()
	$('.question form input[type="hidden"][name="question[append_files][]"]').remove()
	$('.question form #question_append_files').val(null)
	$('.question form #question_append_files').prop('disabled', false)
	$('.question .remove-attachment-link').hide()
	$('.question .remove-link-link').hide()
	$('.question .edit-question-link').show()
	$('.question .nested-fields').not(':first').remove()
	$('.question .nested-fields div :text').val(null)
	$('.notice').html('<%= notice %>')
<% end %>